create table member (
                        uid varchar(255) primary key,
                        id varchar(10) not null,
                        password varchar(10) not null,
                        name varchar(10) not null,
                        birthday date not null,
                        address varchar(255) not null,
                        phone_number varchar(11) not null,
                        prefer_position int not null,
                        level int not null,
                        phone_number_disclosure_option int not null,
                        join_date date not null,
                        recent_login_date date not null
) engine=InnoDB default charset=utf8;
